name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: "Cargo.toml"
          field: "package.version"
      - run: |
          git tag ${{ steps.read_toml.outputs.value }}
          git push origin ${{ steps.read_toml.outputs.value }}
